# Generated by Django 3.0.6 on 2020-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('opA', models.CharField(max_length=100)),
                ('opB', models.CharField(max_length=100)),
                ('opC', models.CharField(max_length=100)),
                ('opD', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
