# Generated by Django 3.0.6 on 2021-02-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_questionbankcm_questionbankpl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionBank',
            new_name='Aptitude',
        ),
        migrations.RenameModel(
            old_name='QuestionBankCM',
            new_name='Communication',
        ),
        migrations.RenameModel(
            old_name='QuestionBankPL',
            new_name='ProgrammingLogic',
        ),
    ]
